baseURL = "/"
languageCode = "en-us"
title = "Tremor"
theme = "tremor"
description = "Tremor is an early stage event processing system for unstructured data with rich support for structural pattern matching, filtering and transformation"
Paginate = 6

# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = false
# pygmentsStyle                 = "monokai"

[Params]
  RSSLink = "/index.xml"
  author = "The Tremor Team" # add your company name
  github = "tremor-rs" # add your github profile name
  twitter = "TremorDEBS" # add your twitter profile
  email = "#"

[[menu.main]]
    name = "Blog"
    weight = 100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = 200
    url = "/faq/"
[[menu.main]]
    name = "Getting Started"
    weight = 300
    url = "/getting-started/"
[[menu.main]]
    name = "Docs"
    weight = 400
    url = "https://docs.tremor.rs/"
[[menu.main]]
    name = "RFCs"
    weight = 500
    url = "https://rfcs.tremor.rs/"
[[menu.main]]
    name = "Community"
    weight = 600
    url = "/community/"
[[menu.main]]
    name = "Governance"
    weight = 700
    url = "/governance/"
[[menu.main]]
    name = "Chat"
    weight = 800
    url = "https://cloud-native.slack.com/messages/tremor"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 4
